version: "3"

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: snapping-rails/snapping-rails-api:latest
    profiles: ["not-postgres"]
    ports:
      - "5000:5000"
    depends_on:
      - redis

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: snapping-rails/snapping-rails-web:latest
    profiles: ["not-postgres"]
    ports:
      - "3000:3000"
    depends_on:
      - api

  nginx:
    build: ./nginx
    profiles: ["not-postgres"]
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - api
      - web

  db:
    image: postgres
    container_name: snapping-rails-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    profiles: ["not-postgres"]
    container_name: snapping-rails-redis

volumes: 
  pgdata:
