version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: snapping-rails/snapping-rails-api:latest
    ports:
      - "5000:5000"
    networks:
      - snapping-net
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: snapping-rails/snapping-rails-web:latest
    ports:
      - "3000:3000"
    networks:
      - snapping-net
    depends_on:
      - api

  db:
    image: postgres
    container_name: snapping-rails-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - snapping-net

volumes: 
  pgdata:

networks:
  snapping-net:
    external: true
