name: Jest (Web) CI

on:
  push:
    paths:
    - 'web/**'
    - '.github/workflows/web-ci.yml'

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Env and Run Tests
        uses: actions/setup-node@v1
        with:
          node-version: '17.7.1'
      - run: |
          cd web
          npm install
          npm test
